#-------------------------------
# General Site Settings
title: Hella Consulting
bio: "Web3 Native Fractional engineering, DevRel, Digital Marketing & Strategy"
description: "Web3 Native Fractional engineering, DevRel, Digital Marketing & Strategy"
reading_time: false
logo: "assets/images/logo.png"
background: "assets/images/bg.png"
event-image: assets/images/consensus2025.png
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: https://anataliocs.github.io
baseurl: /hella-site-base

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed