#-------------------------------
# Site Settings
title: Hella
description: Hella Consulting - Web3 Native Fractional Engineering, DevRel, Digital Marketing & Strategy
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:
baseurl: /hella-site-base

#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - url: '/services/'
      title: 'Services'
    - url: '/team/'
      title: 'Team'
    - url: '/contact/'
      title: 'Contact'

#-------------------------------
# Author Settings
author:
  author_name: Chris Anatalio
  author_avatar: /images/chris1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Hella
  hero_subtitle: Web3-Native Fractional Engineering, DevRel, Digital Marketing & Strategy
  hero_description: |
    Full-service consultancy with broad experience across Web2, Enterprise and Web3
  hero_image: /images/101.jpg
  hero_button_text: Let's Go
  hero_button_link: '/contact/'

# Logos
logos:
  enable: true
  logos_title: Our Team
  logo_image:
    - alt: "Chris Anatalio"
      image: "/images/chris1.jpg"
    - alt: "Anna Lopatina"
      image: "/images/anna1.jpg"
    - alt: "Placeholder"
      image: "/images/02.jpg"

#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Topic Zero Blog

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Monthly Up-level ✌️
  mailchimp_description: Actionable tips and alpha for enhancing productivity from an industry veterans.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email...
  mailchimp_button_text: No fluff, Just Value


#-------------------------------
# Footer Settings
footer_description: Get inspired, find guidance and up-level your skillset!


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/CAnatalio"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/anataliocs"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: inbound@email.com # Add your form_id
  button_text: Let's go

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id